### PR TITLE
Release 1.4.1

### PR DESCRIPTION
**Pull request by ywkim312**
This is a pyincore-viz 1.4.1 release. The only changes was to add palettable>=3.3.0 and plcursors>=0.5.1 to requirements.txt

### CODE REVIEW

**Comment by navarroc** [comment]
Can you fix the merge conflicts? I don't know why, but for some reason we are getting conflicts when we merge release -> master, then master -> develop.

**Comment by ywkim312** [comment]
> Can you fix the merge conflicts? I don't know why, but for some reason we are getting conflicts when we merge release -> master, then master -> develop.

Wow, this is super weird. I can guarantee that there was no merge conflict when I asked to review this PR this morning. Anyway, fixed those conflicts...

**Review by longshuicy — APPROVED** [review]

**Comment by navarroc** [comment]
Are you going to create an RC version of this on anaconda.org for testing the library additions?

**Comment by ywkim312** [comment]
> Are you going to create an RC version of this on anaconda.org for testing the library additions?

Yes I am making it now and should be there before 1:45pm 12/06/21 Monday

**Review by navarroc — APPROVED** [review]

**Pull request merged**
