### PR TITLE
Apply black format

### PR DESCRIPTION
**Pull request by ylyangtw**

### CODE REVIEW

**Comment by navarroc** [comment]
Just an FYI - the fix for pytest is in mine and @ywkim312 's PR here - https://github.com/IN-CORE/pyincore-viz/pull/172. If we merge that first, we can then bring that into this PR.

**Review by navarroc — CHANGES_REQUESTED** [review]
pre-commit run --all-files fails - unused import in geoutil.py

**Comment by ylyangtw** [comment]
> pre-commit run --all-files fails - unused import in geoutil.py

it's addressed!

**Review by navarroc — APPROVED** [review]

**Review by ywkim312 — APPROVED** [review]
test worked well

**Pull request merged**
