### PR TITLE
match curve fields

### PR DESCRIPTION
**Pull request by longshuicy**
To Test:
- install the latest develop branch of pyincore in a conda environment
- in the same conda environment run pytest `test_pyincore_viz.py`. You only need to run the `def test_plot_fragility(client):` function inside.

### CODE REVIEW

**Review by nunezco2 — APPROVED** [review]

**Comment by ywkim312** [comment]
> To Test:
> 
> * install the latest develop branch of pyincore in a conda environment
> * in the same conda environment run pytest `test_pyincore_viz.py`. You only need to run the `def test_plot_fragility(client):` function inside.

I published the pyincore.1.2.0.rc.4 using the latest develop branch of pyincore. You can try this when reviewing if you want to install it.

**Comment by ywkim312** [comment]
I got an error saying ```ImportError: cannot import name 'StandardFragilityCurve' from 'pyincore'```
I was not able to find StandardFragilityCurve method in pyincore package.

**Comment by vnarah2** [comment]
> I got an error saying `ImportError: cannot import name 'StandardFragilityCurve' from 'pyincore'`
> I was not able to find StandardFragilityCurve method in pyincore package. Maybe I am doing something wrong?

@ywkim312 StandardFragilityCurve class has been deprecated. The error is legit. If there are references to 'StandardFragilityCurve' in viz/plotting service, they should be removed

**Review by ywkim312 — APPROVED** [review]
test_pyincore_viz worked. I approve

**Pull request merged**
